In [262]:
import warnings
warnings.filterwarnings('ignore')
import neurokit2 as nk
import numpy as np
import pandas as pd

In [263]:
Simulated_ECG = nk.ecg_simulate(duration=2000, sampling_rate=1,noise=0.01, heart_rate=100)
Simulated_ECG.mean()

0.12174371080601322

In [264]:
Simulated_ECG2 = nk.ecg_simulate(duration=15, sampling_rate=200,noise=0.01, heart_rate=100)
Simulated_ECG2.mean()

0.11980629256939822

In [265]:
(Simulated_ECG2==Simulated_ECG)

False

In [266]:
def generer_ECG_moy_data_patient(n_patients):
    l=[]
    d=0
    for i in range(n_patients):
        Simulated_ECG = nk.ecg_simulate(duration=15, sampling_rate=200,noise=0.01, heart_rate=100)
        d=Simulated_ECG.mean()
        l.append(d)
    return l

In [267]:
l=generer_ECG_data_patient(150)

In [268]:
import pandas as pd
data_patients=pd.DataFrame(l,columns=["ECG_moy_of_patients"])

In [269]:
data_patients

     ECG_moy_of_patients
0               0.128409
1               0.113618
2               0.127685
3               0.133943
4               0.133985
..                   ...
145             0.124141
146             0.122317
147             0.124954
148             0.116885
149             0.137365

[150 rows x 1 columns]

In [270]:
def generer_RSP_moy_data_patient(n):
    lst=[]
    d=0
    for i in range(n):
        rsp_sim = nk.rsp_simulate(duration=15, sampling_rate=200,noise=0.01,respiratory_rate=100, method="sinusoidal")
        d=rsp_sim.mean()
        lst.append(d)
    return lst

In [271]:
lst=generer_RSP_data_patient(150)

In [272]:
data_patients.insert(1,"RSP_moy_of_patients",lst,True)

In [273]:
data_patients

     ECG_moy_of_patients  RSP_moy_of_patients
0               0.128409            -0.000730
1               0.113618            -0.000480
2               0.127685            -0.000240
3               0.133943             0.000736
4               0.133985             0.000788
..                   ...                  ...
145             0.124141             0.000330
146             0.122317            -0.000714
147             0.124954             0.001170
148             0.116885            -0.001320
149             0.137365            -0.000328

[150 rows x 2 columns]

In [274]:
import pandas as pd
import numpy as np
def generer_body_temp_moy_data_patient(temp_min,temp_max,n):
    lst=[]
    d=0
    for i in range(n):
        rng = np.random.RandomState(1)
        a=(temp_max-temp_min)/n
        body_temp = rng.uniform(temp_min, temp_max, size=3000)
        d=body_temp.mean()
        temp_min+=a
        lst.append(d)
    return lst

In [275]:
lst=generer_body_temp_moy_data_patient(95,104,150)

In [276]:
lst

[99.50110495476918,
 99.53109758840407,
 99.56089027114804,
 99.59048433600704,
 99.61988110710034,
 99.64908189971966,
 99.67808802038822,
 99.70690076691893,
 99.73552142847281,
 99.76395128561634,
 99.79219161037888,
 99.82024366630971,
 99.8481087085343,
 99.87578798381072,
 99.90328273058533,
 99.9305941790481,
 99.95772355118778,
 99.98467206084655,
 100.01144091377422,
 100.03803130768237,
 100.06444443229783,
 100.09068146941586,
 100.11674359295307,
 100.14263196900006,
 100.16834775587338,
 100.19389210416757,
 100.21926615680646,
 100.2444710490944,
 100.26950790876712,
 100.294377856042,
 100.31908200366838,
 100.34362145697725,
 100.36799731393073,
 100.3922106651712,
 100.41626259407005,
 100.44015417677626,
 100.46388648226441,
 100.48746057238264,
 100.51087750190011,
 100.53413831855411,
 100.55724406309707,
 100.58019576934309,
 100.60299446421415,
 100.62564116778606,
 100.64813689333414,
 100.67048264737858,
 100.6926794297294,
 100.71472823353119,
 100.73663004530766,
 100.75838584500559,
 100.77999660603888,
 100.80146329533198,
 100.8227868733631,
 100.84396829420736,
 100.86500850557928,
 100.88590844887541,
 100.90666905921628,
 100.92729126548815,
 100.9477759903849,
 100.96812415044903,
 100.9883366561127,
 101.0084144117386,
 101.02835831566034,
 101.04816926022261,
 101.06784813182112,
 101.08739581094233,
 101.10681317220269,
 101.12610108438801,
 101.14526041049207,
 101.16429200775546,
 101.18319672770376,
 101.20197541618572,
 101.22062891341118,
 101.23915805398843,
 101.25756366696186,
 101.27584657584876,
 101.29400759867643,
 101.31204754801858,
 101.32996723103182,
 101.34776744949158,
 101.36544899982832,
 101.38301267316278,
 101.40045925534169,
 101.41778952697274,
 101.43500426345959,
 101.45210423503653,
 101.46909020680296,
 101.4859629387576,
 101.50272318583255,
 101.51937169792699,
 101.53590921994082,
 101.55233649180786,
 101.56865424852916,
 101.58486322020565,
 101.60096413207093,
 101.61695770452381,
 101.6328446531603,
 101.64862568880591,
 101.66430151754719,
 101.67987284076354,
 101.69534035515844,
 101.71070475279072,
 101.72596672110546,
 101.74112694296475,
 101.75618609667833,
 101.77114485603379,
 101.78600389032691,
 101.8007638643914,
 101.81542543862878,
 101.82998926903792,
 101.84445600724433,
 101.85882630052937,
 101.87310079185917,
 101.88728011991346,
 101.90136491911404,
 101.9153558196533,
 101.92925344752226,
 101.94305842453878,
 101.9567713683752,
 101.970392892586,
 101.98392360663544,
 101.99736411592454,
 102.01071502181837,
 102.02397692167291,
 102.03715040886178,
 102.05023607280269,
 102.063234498984,
 102.07614626899078,
 102.08897196053086,
 102.10171214746065,
 102.11436739981089,
 102.12693828381215,
 102.13942536192008,
 102.15182919284061,
 102.164150331555,
 102.17638932934463,
 102.18854673381568,
 102.20062308892355,
 102.21261893499742,
 102.22453480876408,
 102.23637124337233,
 102.24812876841654,
 102.25980790996039,
 102.27140919056065,
 102.28293312929026,
 102.29438024176166,
 102.3057510401499,
 102.31704603321559,
 102.32826572632747,
 102.33941062148529]

In [277]:
data_patients.insert(1,"body_temp_moy_of_patients",lst,True)

In [278]:
data_patients

     ECG_moy_of_patients  body_temp_moy_of_patients  RSP_moy_of_patients
0               0.128409                  99.501105            -0.000730
1               0.113618                  99.531098            -0.000480
2               0.127685                  99.560890            -0.000240
3               0.133943                  99.590484             0.000736
4               0.133985                  99.619881             0.000788
..                   ...                        ...                  ...
145             0.124141                 102.294380             0.000330
146             0.122317                 102.305751            -0.000714
147             0.124954                 102.317046             0.001170
148             0.116885                 102.328266            -0.001320
149             0.137365                 102.339411            -0.000328

[150 rows x 3 columns]

In [279]:
from simglucose.simulation.env import T1DSimEnv
from simglucose.controller.basal_bolus_ctrller import BBController
from simglucose.sensor.cgm import CGMSensor
from simglucose.actuator.pump import InsulinPump
from simglucose.patient.t1dpatient import T1DPatient
from simglucose.simulation.scenario_gen import RandomScenario
from simglucose.simulation.scenario import CustomScenario
from simglucose.simulation.sim_engine import SimObj, sim, batch_sim
from datetime import timedelta
from datetime import datetime

In [280]:
# specify start_time as the beginning of today
dt = datetime(2022,5,20,22,16,0)
now = datetime.now()
start_time = datetime.combine(dt.date(), datetime.min.time())

def generer_CGM_moy_and_insulin_moy(n_patients):
    lst1=[]
    lst2=[]
    for i in range(n_patients):
        dt = datetime(2022,6,12,20,16,0)
        now = datetime.now()
        start_time = datetime.combine(dt.date(), datetime.min.time())
        path = './results'
        # Create a simulation environment
        patient = T1DPatient.withName('adolescent#00{}'.format(i))
        sensor = CGMSensor.withName('Dexcom', seed=1)
        pump = InsulinPump.withName('Insulet')
        scenario = RandomScenario(start_time=start_time, seed=1)
        env = T1DSimEnv(patient, sensor, pump, scenario)
        # Create a controller
        controller = BBController()
        s1 = SimObj(env,controller, timedelta(days=7), animate=False, path=path)
        results1 = sim(s1)
        data2=pd.DataFrame(results1)
        lst1+=data2['CGM'].mean()
        lst2+=data2['insulin'].mean()
    return lst1,lst2

In [281]:
# specify start_time as the beginning of today
dt = datetime(2022,5,20,22,16,0)
now = datetime.now()
print(now)
start_time = datetime.combine(dt.date(), datetime.min.time())

# --------- Create Random Scenario --------------
# Specify results saving path
path = './results'

# Create a simulation environment
patient = T1DPatient.withName('adolescent#001')
sensor = CGMSensor.withName('Dexcom', seed=1)
pump = InsulinPump.withName('Insulet')
scenario = RandomScenario(start_time=start_time, seed=1)
env = T1DSimEnv(patient, sensor, pump, scenario)

# Create a controller
controller = BBController()

# Put them together to create a simulation object
s1 = SimObj(env, controller, timedelta(days=7), animate=False, path=path)
results1 = sim(s1)
print(results1)
data2=pd.DataFrame(results1)

2022-06-12 22:59:03.128261
Process ID: 2456
Simulation starts ...
Simulation Completed!
                             BG         CGM  CHO   insulin      LBGI  \
Time
2022-05-20 00:00:00  149.020000  165.793949  0.0  0.013933  0.000000
2022-05-20 00:03:00  149.020000  161.582022  0.0  0.013933  0.000000
2022-05-20 00:06:00  149.020000  159.239373  0.0  0.013933  0.000000
2022-05-20 00:09:00  149.020000  157.472710  0.0  0.013933  0.000000
2022-05-20 00:12:00  149.020000  156.108950  0.0  0.013933  0.000000
...                         ...         ...  ...       ...       ...
2022-05-26 23:48:00   89.506730   82.020860  0.0  0.013933  1.810508
2022-05-26 23:51:00   90.019792   83.620499  0.0  0.013933  1.721358
2022-05-26 23:54:00   90.533411   85.494805  0.0  0.013933  1.634845
2022-05-26 23:57:00   91.047723   87.698967  0.0  0.013933  1.550913
2022-05-27 00:00:00   91.562845   90.154322  NaN       NaN  1.469512

                         HBGI      Risk
Time
2022-05-20 00:00:00  2.755276  2.755276
2022-05-20 00:03:00  2.755276  2.755276
2022-05-20 00:06:00  2.755276  2.755276
2022-05-20 00:09:00  2.755276  2.755276
2022-05-20 00:12:00  2.755276  2.755276
...                       ...       ...
2022-05-26 23:48:00  0.000000  1.810508
2022-05-26 23:51:00  0.000000  1.721358
2022-05-26 23:54:00  0.000000  1.634845
2022-05-26 23:57:00  0.000000  1.550913
2022-05-27 00:00:00  0.000000  1.469512

[3361 rows x 7 columns]

In [282]:
data_glucose_insulin=data2[["CGM","insulin"]]

In [283]:
data_glucose_insulin_V2=data_glucose_insulin.reset_index()

In [284]:
data_patients.insert(1,"CGM_of_patients",data_glucose_insulin_V2["CGM"],True)

In [285]:
data_patients.insert(1,"insulin_of_patients",data_glucose_insulin_V2["insulin"],True)

In [286]:
data_patients

,ECG_moy_of_patients,insulin_of_patients,CGM_of_patients,body_temp_moy_of_patients,RSP_moy_of_patients
0,0.128409,0.013933,165.793949,99.501105,-0.000730
1,0.113618,0.013933,161.582022,99.531098,-0.000480
2,0.127685,0.013933,159.239373,99.560890,-0.000240
3,0.133943,0.013933,157.472710,99.590484,0.000736
4,0.133985,0.013933,156.108950,99.619881,0.000788
...,...,...,...,...,...
145,0.124141,0.013933,149.037257,102.294380,0.000330
146,0.122317,0.013933,148.696840,102.305751,-0.000714
147,0.124954,0.013933,147.642914,102.317046,0.001170
148,0.116885,0.013933,145.737046,102.328266,-0.001320
149,0.137365,0.013933,144.030844,102.339411,-0.000328

In [287]:
l=["Patient N°{}".format(i) for i in range(1,151)]

In [288]:
data_patients.insert(0,"Ids",l,True)

In [289]:
data_patients

,Ids,ECG_moy_of_patients,insulin_of_patients,CGM_of_patients,body_temp_moy_of_patients,RSP_moy_of_patients
0,Patient N°1,0.128409,0.013933,165.793949,99.501105,-0.000730
1,Patient N°2,0.113618,0.013933,161.582022,99.531098,-0.000480
2,Patient N°3,0.127685,0.013933,159.239373,99.560890,-0.000240
3,Patient N°4,0.133943,0.013933,157.472710,99.590484,0.000736
4,Patient N°5,0.133985,0.013933,156.108950,99.619881,0.000788
...,...,...,...,...,...,...
145,Patient N°146,0.124141,0.013933,149.037257,102.294380,0.000330
146,Patient N°147,0.122317,0.013933,148.696840,102.305751,-0.000714
147,Patient N°148,0.124954,0.013933,147.642914,102.317046,0.001170
148,Patient N°149,0.116885,0.013933,145.737046,102.328266,-0.001320
149,Patient N°150,0.137365,0.013933,144.030844,102.339411,-0.000328

In [290]:
data_patients = data_patients.set_index('Ids')

In [291]:
data_patients

,ECG_moy_of_patients,insulin_of_patients,CGM_of_patients,body_temp_moy_of_patients,RSP_moy_of_patients
Ids,,,,,
Patient N°1,0.128409,0.013933,165.793949,99.501105,-0.000730
Patient N°2,0.113618,0.013933,161.582022,99.531098,-0.000480
Patient N°3,0.127685,0.013933,159.239373,99.560890,-0.000240
Patient N°4,0.133943,0.013933,157.472710,99.590484,0.000736
Patient N°5,0.133985,0.013933,156.108950,99.619881,0.000788
...,...,...,...,...,...
Patient N°146,0.124141,0.013933,149.037257,102.294380,0.000330
Patient N°147,0.122317,0.013933,148.696840,102.305751,-0.000714
Patient N°148,0.124954,0.013933,147.642914,102.317046,0.001170
Patient N°149,0.116885,0.013933,145.737046,102.328266,-0.001320
Patient N°150,0.137365,0.013933,144.030844,102.339411,-0.000328